### ISSUE TITLE
phys2d error with sbt then error on com.github.dunnololda.state.State

### ISSUE THREAD

**Issue by RMKD** [dunnololda/scage#11]
Came across this and gave it a spin. Am I missing something obvious on how to get started? 

ran `sbt compile`
```
sbt.ResolveException: download failed: phys2d#phys2d;060408!phys2d.zip
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:165)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:127)
	at sbt.IvySbt.withIvy(Ivy.scala:124)
	at sbt.IvySbt$Module.withModule(Ivy.scala:155)
	at sbt.IvyActions$.updateEither(IvyActions.scala:165)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1369)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1365)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1399)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$87.apply(Defaults.scala:1397)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1402)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1396)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1419)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1348)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1310)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: download failed: phys2d#phys2d;060408!phys2d.zip

```

ran `sbt update`
```
[info] Loading project definition from ~/tools/scage/project
[info] Set current project to scage (in build file:~/tools/scage/)
[info] Patching ~/.ivy2/cache/phys2d/phys2d/ivy-060408.xml ...
[info] Done.
[info] Updating {file:~/tools/scage/}scage...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://raw.github.com/dunnololda/mvn-repo/master/phys2d/phys2d/060408/phys2d-060408.jar ...
[info] 	[SUCCESSFUL ] phys2d#phys2d;060408!phys2d.jar (2966ms)
[info] Done updating.
```

ran `sbt compile`
```
[info] Loading project definition from ~/tools/scage/project
[info] Set current project to scage (in build file:~/tools/scage/)
[info] Patching ~/.ivy2/cache/phys2d/phys2d/ivy-060408.xml ...
[info] Done.
[info] Compiling 33 Scala sources and 7 Java sources to ~/tools/scage/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.1. Compiling...
[info]   Compilation completed in 13.929 s
[error] ~/tools/scage/src/main/scala/com/github/dunnololda/scage/ScageLib.scala:309: object state is not a member of package com.github.dunnololda
[error]   val State            = com.github.dunnololda.state.State
[error]                                                ^
[error] ~/tools/scage/src/main/scala/com/github/dunnololda/scage/support/ScageColor.scala:3: object mysimplelogger is not a member of package com.github.dunnololda
[error] import com.github.dunnololda.mysimplelogger.MySimpleLogger
```

tried the maven command listed in the README
```
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: project-archetype:10.3
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: scage
[INFO] Parameter: artifactId, Value: project-archetype
[INFO] Parameter: version, Value: 10.3
[INFO] Parameter: package, Value: com.github.dunnololda.scage
[INFO] Parameter: packageInPathFormat, Value: com/github/dunnololda/scage
[INFO] Parameter: package, Value: com.github.dunnololda.scage
[INFO] Parameter: version, Value: 10.3
[INFO] Parameter: groupId, Value: scage
[INFO] Parameter: artifactId, Value: project-archetype
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:25 min
[INFO] Finished at: 2015-06-13T08:51:12-04:00
[INFO] Final Memory: 16M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.3:generate (default-cli) on project scage_2.10: org.apache.maven.archetype.exception.InvalidPackaging: Unable to add module to the current project as it is not of packaging type 'pom' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by dunnololda** [comment]
Hello! Sorry for the delay.

About sbt: 
I updated some dependencies, everything should work now. This works for me:
$ sbt phys2D-patch
$ sbt update
$ sbt comple

About maven:
I tested this command:
mvn archetype:generate -DarchetypeGroupId=scage -DarchetypeArtifactId=project-archetype -DarchetypeVersion=10.3 -DarchetypeRepository=https://raw.github.com/dunnololda/mvn-repo/master

on a fresh computer with only java and maven installed, and it works. What maven version do you use? I tested with maven 3.0.5, downloaded from there:
https://maven.apache.org/download.cgi

I suppose, 3.0.5 and higher are fine, maven 2.x maybe not.

If you have any other questions, please ask. Good luck!)

**Comment by dunnololda** [comment]
Seems, I can close the issue)
